// <auto-generated />
using System;
using GAC.Warehouse.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GAC.Warehouse.Migrations.Customer
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20200822045017_initcdbcontextwithseed")]
    partial class initcdbcontextwithseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IO.Swagger.Models.Customer", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailID")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EmailID = "uncle@gmail.com",
                            Name = "CustomerA",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            ID = 2,
                            EmailID = "bob@gmail.com",
                            Name = "CustomerB",
                            PhoneNumber = "1234567891"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
