/*
 * Warehouse API
 *
 * Warehouse API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations.Schema;

namespace IO.Swagger.Models
{
  /// <summary>
  /// 
  /// </summary>
  [DataContract]
  public partial class Customer : IEquatable<Customer>
  {
    /// <summary>
    /// Gets or Sets ID
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [DataMember(Name = "ID")]
    public int? ID { get; set; }

    /// <summary>
    /// Gets or Sets Name
    /// </summary>
    [Required]
    [DataMember(Name = "Name")]
    public string Name { get; set; }

    /// <summary>
    /// Gets or Sets PhoneNumber
    /// </summary>
    [Required]
    [DataMember(Name = "PhoneNumber")]
    public string PhoneNumber { get; set; }

    /// <summary>
    /// Gets or Sets EmailID
    /// </summary>
    [Required]
    [DataMember(Name = "EmailID")]
    public string EmailID { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
      var sb = new StringBuilder();
      sb.Append("class Customer {\n");
      sb.Append("  ID: ").Append(ID).Append("\n");
      sb.Append("  Name: ").Append(Name).Append("\n");
      sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
      sb.Append("  EmailID: ").Append(EmailID).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      return obj.GetType() == GetType() && Equals((Customer)obj);
    }

    /// <summary>
    /// Returns true if Customer instances are equal
    /// </summary>
    /// <param name="other">Instance of Customer to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(Customer other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;

      return
          (
              ID == other.ID ||
              ID != null &&
              ID.Equals(other.ID)
          ) &&
          (
              Name == other.Name ||
              Name != null &&
              Name.Equals(other.Name)
          ) &&
          (
              PhoneNumber == other.PhoneNumber ||
              PhoneNumber != null &&
              PhoneNumber.Equals(other.PhoneNumber)
          ) &&
          (
              EmailID == other.EmailID ||
              EmailID != null &&
              EmailID.Equals(other.EmailID)
          );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
      unchecked // Overflow is fine, just wrap
      {
        var hashCode = 41;
        // Suitable nullity checks etc, of course :)
        if (ID != null)
          hashCode = hashCode * 59 + ID.GetHashCode();
        if (Name != null)
          hashCode = hashCode * 59 + Name.GetHashCode();
        if (PhoneNumber != null)
          hashCode = hashCode * 59 + PhoneNumber.GetHashCode();
        if (EmailID != null)
          hashCode = hashCode * 59 + EmailID.GetHashCode();
        return hashCode;
      }
    }

    #region Operators
#pragma warning disable 1591

    public static bool operator ==(Customer left, Customer right)
    {
      return Equals(left, right);
    }

    public static bool operator !=(Customer left, Customer right)
    {
      return !Equals(left, right);
    }

#pragma warning restore 1591
    #endregion Operators
  }
}
